# Taps
tap 'caskroom/cask'
tap 'caskroom/eid'
tap 'caskroom/fonts'
tap 'caskroom/versions'
tap 'homebrew/bundle'

brew 'librsvg'
brew 'openssl'
brew 'ansible'
brew 'ansible-lint'
brew 'autoconf'
brew 'automake'
brew 'bash-completion'
brew 'bats'
brew 'bats-core'
brew 'curl'
brew 'cloc'
brew 'cmake'
brew 'mas'
brew 'git'
brew 'git-lfs'
brew 'gnupg'
brew 'highlight'
brew 'lftp'
brew 'mongodb'
brew 'ncurses'
brew 'nano'
brew 'nmap'
brew 'p7zip'
brew 'poppler'
brew 'pdf2svg'
brew 'shellcheck'
brew 'tree'
brew 'htop'
brew 'wget'
brew 'jq'
brew 'hub'
brew 'mysql-client'
brew 'proselint'
brew 'grep'

cask 'miniconda'
cask 'atom'
cask 'docker'
cask 'dropbox'
cask 'firefox'
cask 'google-backup-and-sync'
cask 'google-chrome'
cask 'java'
cask 'skype'
cask 'slack'
cask 'mactex'
cask 'meld'
cask 'mendeley'
cask 'robo-3t'
cask 'sourcetree'
cask 'spotify'
cask 'whatsapp'
cask 'adobe-acrobat-reader'
cask 'keepingyouawake'
cask 'sequel-pro'
cask 'tunnelblick'
cask 'zoomus'

# requires java
brew 'umlet'

# Quicklook
cask 'qlcolorcode'
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'quicklook-csv'
cask 'qlstephen'

mas 'The Unarchiver', id: 425424353
mas 'Magnet', id: 441258766
